# Generated by Django 4.1.13 on 2024-04-02 20:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
