# Generated by Django 5.0.4 on 2024-04-08 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"managed": False},
        ),
    ]
