# Generated by Django 5.0.4 on 2024-04-09 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="blog",
        ),
    ]
