# Generated by Django 5.0.4 on 2024-04-11 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blog_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
    ]
